# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

N = int(input())

x = 0
c = 0

while x < N:
  x +=1
  a = int(input())
  if a==0:
    c+=1
print("Количество нулей=",c)