# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

x = int(input())


c = 0
if x <= 2e9:
  for i in range(1, x+1):
    if x % i == 0:
      c+=1
  print(c)
else:
  print(False)