# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

A = int(input())
B = int(input())



for i in range(A,B+1):
  if i%2 == 0:
    print(i, end=' ')